services:
  postgres:
    image: postgres:16
    container_name: journalapp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: journaluser
      POSTGRES_PASSWORD: journalpassword
      POSTGRES_DB: journalapp
    ports:
      - "5432:5432"
    volumes:
      - journalapp_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: journalapp-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  journalapp_postgres_data: